coding_dict = {
    "CSE1235": {
        "file_path": "M:/CPP-Data/Sutherland RPA/Coding/CSE1235",
        "columns": [
            "PTFULLNAME",
            "INVNUM",
            "CRN#",
            "RetrievalStatus",
            "RetrievalDescription",
            "Reason",
            "RD + Reason",
            "Business Status",
            "Business Scenario",
        ],
        "status_crosswalk": {
            "Specified Process Failure - After Refile Encounter": "Exception",
            "Validation Error - Encounter Number": "Exception",
            "End-to-End Success - CPT Updated to EST": "Success",
            "Unable to Click Hyperlink - Batch on Hold": "Exception",
            "Missing Mandatory Field - Missing Enc/Txn Number": "Exception",
            "New/Unexpected Screen Element - Procedure Code": "Exception",
            "Account Not Found - No Patient Found": "Exception",
            "Review Required by Northwell - Pending Representative Review": "Exception",
            "New/Unexpected Screen Element - IDX": "Exception",
            "Crosswalk Discrepancy - Input CPT not on Crosswalk": "Exception",
            "Unable to Click Hyperlink - Pending Representative Review": "Exception",
            "Specified Process Failure - Update Task Process": "Exception",
            "Unspecified Technical Failure - ": "Exception",
        },
        "scenario_crosswalk": {
            "Specified Process Failure - After Refile Encounter": "Technical error did not recognize a completed transaction",
            "Validation Error - Encounter Number": "Unable to validate encounter number",
            "End-to-End Success - CPT Updated to EST": "Successful transaction",
            "Unable to Click Hyperlink - Batch on Hold": "'Edit Transaction' hyperlink is not available; Likely Batch on Hold",
            "Missing Mandatory Field - Missing Enc/Txn Number": "Input File does not contain mandatory Enc/Txn numbers",
            "New/Unexpected Screen Element - Procedure Code": "Procedure Codes do not populate in Enc/Txn screens",
            "Account Not Found - No Patient Found": "No search results for patient; Likely worked by another user",
            "Review Required by Northwell - Pending Representative Review": "Business rules applied to pend txn for further review",
            "New/Unexpected Screen Element - IDX": "Unexpected IDX Pop up",
            "Crosswalk Discrepancy - Input CPT not on Crosswalk": "Input CPT does not have a value on the CPT Crosswalk",
            "Unable to Click Hyperlink - Pending Representative Review": "Technical Error prevented the bot from clicking the Pending Rep Review hyperlink",
            "Specified Process Failure - Update Task Process": "Technical Error prevented the bot from adding a note to the transaction",
            "Unspecified Technical Failure - ": "Unspecified technical error",
        },
        "column_crosswalk": {
            "PTFULLNAME": "Patient Name",
            "INVNUM": "Enc Number",
            "CRN#": "Txn Number",
            "RetrievalStatus": "Retrieval Status",
            "RetrievalDescription": "Retrieval Description",
            "Reason": "Reason",
        },
        "carbon_copy": 'klawrence3@northwell.edu; ovicuna@northwell.edu; jcarney1@northwell.edu; gbunce@northwell.edu; mpuma@northwell.edu',
        "name_format": "{file_path}/GECB_CSE1235_Outbound_{month_str}{day_str}{year_str}.xlsx",
    },
    "CSE1236": {
        "file_path": "M:/CPP-Data/Sutherland RPA/Coding/CSE1236",
        "columns": [
            "PTFULLNAME",
            "INVNUM",
            "CRN#",
            "RetrievalStatus",
            "RetrievalDescription",
            "Reason",
            "RD + Reason",
            "Business Status",
            "Business Scenario",
        ],
        "status_crosswalk": {
            "Crosswalk Discrepancy - Input CPT not on Crosswalk":"Exception",
            "New/Unexpected Screen Element - No CPT populated":"Exception",
            "Specified Process Failure - Edit Multiple Enc/Trans":"Exception",
            "Specified Process Failure - Unrecognized Success After Refile":"Exception",
            "New/Unexpected Screen Element - Enc Table in TES Enc/Txn Edit screen":"Exception",
            "Validation Error - Encounter Number":"Exception",
            "Unable to Click Hyperlink - Batch on Hold":"Exception",
            "Unable to Click Hyperlink - Edit Multi Enc/Trn":"Exception",
            "New/Unexpected Screen Element - Encounter Edit List":"Exception",
            "Missing Mandatory Field - Missing Enc/Txn Number":"Exception",
            "New/Unexpected Screen Element - Procedure Code":"Exception",
            "Validation Error - Within Edit Condition Description":"Exception",
            "Extraction Error - Edit Condition Description":"Exception",
            "New/Unexpected Screen Element - Edit Selector Header Screen":"Exception",
            "Account Not Found - No Patient Found":"Exception",
            "New/Unexpected Screen Element - IDX":"Exception",
            "Known Pop Up - Edit CPT":"Exception",
            "New/Unexpected Screen Element - Enc/Txn Edit Page":"Exception",
            "Specified Process Failure - Update Task Process":"Exception",
            "New/Unexpected Screen Element - Encounter Number":"Exception",
            "Crosswalk Discrepancy - Input CPT not on Crosswalk":"Exception",
            "End-to-End Success - CPT Updated to NEW":"Success",
            "Review Required by Northwell - Pending Representative Review":"Exception",
            "Unspecified Technical Failure - ":"Exception",
        },
        "scenario_crosswalk": {
            "Crosswalk Discrepancy - Input CPT not on Crosswalk":"Input CPT does not match a crosswalk value",
            "New/Unexpected Screen Element - No CPT populated":"Procedure Codes do not populate in Enc/Txn screens",
            "Specified Process Failure - Edit Multiple Enc/Trans":"Technical Error prevents accessing Edit Multi Enc/Trans hyperlink",
            "Specified Process Failure - Unrecognized Success After Refile":"Technical Error prevents recognition of successfully processed transaction",
            "New/Unexpected Screen Element - Enc Table in TES Enc/Txn Edit screen":"Technical Error prevents identification of the Enc/Txn Edit screen",
            "Validation Error - Encounter Number":"Unable to validate encounter number",
            "Unable to Click Hyperlink - Batch on Hold":"'Edit Transaction' hyperlink is not available; Likely Batch on Hold",
            "Unable to Click Hyperlink - Edit Multi Enc/Trn":"Edit Multi Enc/Trn' hyperlink is unavailable; Likely due to Encounter in Use",
            "New/Unexpected Screen Element - Encounter Edit List":"No/Missing edit conditions on Edit Selector Header screen",
            "Missing Mandatory Field - Missing Enc/Txn Number":"Input File does not contain mandatory Enc/Txn numbers",
            "New/Unexpected Screen Element - Procedure Code":"New/Unexpected screen on either Enc/Txn Entry/Edit - Main screen",
            "Validation Error - Within Edit Condition Description":"Unable to validate CPT to be updated from Edit Decription text",
            "Extraction Error - Edit Condition Description":"Technical Error where unable to extract Edit Description text",
            "New/Unexpected Screen Element - Edit Selector Header Screen":"New/Unexpected screen on Edit Selector Header screen",
            "Account Not Found - No Patient Found":"No search results for patient; Likely worked by another user",
            "New/Unexpected Screen Element - IDX":"Unexpected IDX Pop up",
            "Known Pop Up - Edit CPT":"Pop Up while editing 'Proc' value",
            "New/Unexpected Screen Element - Enc/Txn Edit Page":"New/Unexpected screen on either Enc/Txn editing screen",
            "Specified Process Failure - Update Task Process":"Technical Error prevented the bot from adding a note to the transaction",
            "New/Unexpected Screen Element - Encounter Number":"New/Unexpected screen on Patient/Encounter Selection screen",
            "Crosswalk Discrepancy - Input CPT not on Crosswalk":"Input CPT does not match a crosswalk value",
            "End-to-End Success - CPT Updated to NEW":"Successful Transaction",
            "Review Required by Northwell - Pending Representative Review":"Business rules applied to pend txn for further review",
            "Unspecified Technical Failure - ":"Unspecified Technical Error",
        },
        "column_crosswalk": {
            "PTFULLNAME": "Patient Name",
            "INVNUM": "Enc Number",
            "CRN#": "Txn Number",
            "RetrievalStatus": "Retrieval Status",
            "RetrievalDescription": "Retrieval Description",
            "Reason": "Reason",
        },
        "carbon_copy": 'klawrence3@northwell.edu; ovicuna@northwell.edu; jcarney1@northwell.edu; gbunce@northwell.edu; mpuma@northwell.edu',
        "name_format": "{file_path}/GECB_CSE1236_Outbound_{month_str}{day_str}{year_str}.xlsx",
    },
    "TES1249": {
        "file_path": "M:/CPP-Data/Sutherland RPA/Coding/TES1249",
        "columns": [
            "PTFULLNAME",
            "INVNUM",
            "CRN#",
            "RetrievalStatus",
            "RetrievalDescription",
            "Reason",
            "RD + Reason",
            "Business Status",
            "Business Scenario",
        ],
        "status_crosswalk": {
            "New/Unexpected Screen Element - Edit Selector Header Screen":"Exception",
            "New/Unexpected Screen Element - Enc/Txn Edit Page":"Exception",
            "New/Unexpected Screen Element - TES Inquiry Page":"Exception",
            "New/Unexpected Screen Element - View Header Page":"Exception",
            "New/Unexpected Screen Element - Enc Table in TES Enc/Txn Edit screen":"Exception",
            "New/Unexpected Screen Element - Encounter Edit List":"Exception",
            "New/Unexpected Screen Element - Enc 1 in Edit Condition Description":"Exception",
            "New/Unexpected Screen Element - Enc 2 in Edit Condition Description":"Exception",
            "New/Unexpected Screen Element - Diagnosis Code":"Exception",
            "New/Unexpected Screen Element - Procedure Code":"Exception",
            "Crosswalk Discrepancy - Input CPT not on Crosswalk":"Exception",
            "End-to-End Success - Modifier 24 Added":"Success",
            "Extraction Error - Edit Condition Description":"Exception",
            "Known Pop Up - Edit Modifier":"Exception",
            "Known Pop Up - Edit CPT":"Exception",
            "Missing Mandatory Field - Missing Enc/Txn Number":"Exception",
            "New/Unexpected Screen Element - IDX":"Exception",
            "New/Unexpected Screen Element - IDX":"Exception",
            "End-to-End Success - CPT Updated to 99024":"Success",
            "Specified Process Failure - Update Task Process":"Exception",
            "Specified Process Failure - Edit Multiple Enc/Trans":"Exception",
            "Unable to Click Hyperlink - Batch on Hold":"Exception",
            "Unable to Click Hyperlink - Pending Representative Review":"Exception",
            "Unable to Click Hyperlink - Edit Transaction":"Exception",
            "Validation Error - Encounter Number":"Exception",
            "Validation Error - Excessive Edit Descriptions":"Exception",
            "Account Not Found - No Patient Found":"Exception",
            "Review Required by Northwell - Pending Representative Review":"Exception",
            "Unspecified Technical Failure - ":"Exception",
        },
        "scenario_crosswalk": {
            "New/Unexpected Screen Element - Edit Selector Header Screen":"Unable to detect the Edit Selector Header screen",
            "New/Unexpected Screen Element - Enc/Txn Edit Page":"Unable to detect the Enc/Txn Edit Screen",
            "New/Unexpected Screen Element - TES Inquiry Page":"Unable to detect the TES Inquiry Page",
            "New/Unexpected Screen Element - View Header Page":"Unable to detect the View Header screen",
            "New/Unexpected Screen Element - Enc Table in TES Enc/Txn Edit screen":"Unable to detect Enc Table in TES Enc/Txn Edit screen",
            "New/Unexpected Screen Element - Encounter Edit List":"Unable to detect edit conditions on Edit Selector Header screen",
            "New/Unexpected Screen Element - Enc 1 in Edit Condition Description":"Unable to detect encounter # 1 in Edit Condition text",
            "New/Unexpected Screen Element - Enc 2 in Edit Condition Description":"Unable to detect encounter # 2 in Edit Condition text",
            "New/Unexpected Screen Element - Diagnosis Code":"Diagnosis Code has not populated",
            "New/Unexpected Screen Element - Procedure Code":"Procedure Code has not populated",
            "Crosswalk Discrepancy - Input CPT not on Crosswalk":"Input CPT does not match a crosswalk value",
            "End-to-End Success - Modifier 24 Added":"Successfully added Mod 24",
            "Extraction Error - Edit Condition Description":"Unable to extract Edit Condition text",
            "Known Pop Up - Edit Modifier":"Pop Up while editing Modifier",
            "Known Pop Up - Edit CPT":"Pop Up while editing 'Proc'",
            "Missing Mandatory Field - Missing Enc/Txn Number":"Input File does not contain mandatory Enc/Txn numbers",
            "New/Unexpected Screen Element - IDX":"Unexpected IDX Pop up",
            "New/Unexpected Screen Element - IDX":"Unexpected IDX Pop up",
            "End-to-End Success - CPT Updated to 99024":"Successfully update CPT to 99024",
            "Specified Process Failure - Update Task Process":"Technical Error prevented the bot from adding a note to the transaction",
            "Specified Process Failure - Edit Multiple Enc/Trans":"Technical Error prevents accessing Edit Multi Enc/Trans hyperlink",
            "Unable to Click Hyperlink - Batch on Hold":"'Edit Transaction' hyperlink is not available; Likely Batch on Hold",
            "Unable to Click Hyperlink - Pending Representative Review":"Technical Error prevented click of 'Pending Rep Review' hyperlink",
            "Unable to Click Hyperlink - Edit Transaction":"Technical Error prevented click of 'Edit Transaction' Hyperlink",
            "Validation Error - Encounter Number":"Unable to validate encounter number",
            "Validation Error - Excessive Edit Descriptions":"More Edit Descriptions encountered than expected",
            "Account Not Found - No Patient Found":"No search results for patient; Likely worked by another user",
            "Review Required by Northwell - Pending Representative Review":"Business rules applied to pend txn for further review",
            "Unspecified Technical Failure - ":"Unspecified Technical Error",
        },
        "column_crosswalk": {
            "PTFULLNAME": "Patient Name",
            "INVNUM": "Enc Number",
            "CRN#": "Txn Number",
            "RetrievalStatus": "Retrieval Status",
            "RetrievalDescription": "Retrieval Description",
            "Reason": "Reason",
        },
        "carbon_copy": 'klawrence3@northwell.edu; ovicuna@northwell.edu; jcarney1@northwell.edu; gbunce@northwell.edu; mpuma@northwell.edu',
        "name_format": "{file_path}/GECB_TES1249_Outbound_{month_str}{day_str}{year_str}.xlsx",
    },
    "TES6146": {
        "file_path": "M:/CPP-Data/Sutherland RPA/Coding/TES6146",
        "columns": [
            "PTFULLNAME",
            "INVNUM",
            "CRN#",
            "RetrievalStatus",
            "RetrievalDescription",
            "Reason",
            "RD + Reason",
            "Business Status",
            "Business Scenario",
        ],
        "status_crosswalk": {
            "Specified Process Failure - Email Not Sent to Provider":"Exception",
            "New/Unexpected Screen Element - Procedure Code":"Exception",
            "New/Unexpected Screen Element - Diagnosis Code":"Exception",
            "Crosswalk Discrepancy - Input CPT not on Crosswalk":"Exception",
            "End-to-End Success - Dx Pointers Reordered":"Success",
            "Known Pop Up - ICD-CM":"Exception",
            "Known Pop Up - Edit Dx Codes":"Exception",
            "End-to-End Success - Email Sent to Provider":"Success",
            "Missing Mandatory Field - Missing Enc/Txn Number":"Exception",
            "New/Unexpected Screen Element - IDX":"Exception",
            "Review Required by Northwell - Pending Representative Review":"Exception",
            "Specified Process Failure - Update Task Process":"Exception",
            "Specified Process Failure - Update DX Pointers":"Exception",
            "Missing Mandatory Field - Provider Email Address":"Exception",
            "Unable to Click Hyperlink - Batch on Hold":"Exception",
            "Unable to Click Hyperlink - Pending Feedback":"Exception",
            "Unable to Click Hyperlink - Pending Representative Review":"Exception",
            "Validation Error - Encounter Number":"Exception",
            "Account Not Found - No Patient Found":"Exception",
            "Unspecified Technical Failure - ":"Exception",
        },
        "scenario_crosswalk": {
            "Specified Process Failure - Email Not Sent to Provider":"Technical Error prevented email from being sent",
            "New/Unexpected Screen Element - Procedure Code":"Procedure Code has not populated",
            "New/Unexpected Screen Element - Diagnosis Code":"Diagnosis Code has not populated",
            "Crosswalk Discrepancy - Input CPT not on Crosswalk":"Input CPT does not match a crosswalk value",
            "End-to-End Success - Dx Pointers Reordered":"Successfully reordered DX Pointers",
            "Known Pop Up - ICD-CM":"Pop Up stating Dx Code is not specific enough",
            "Known Pop Up - Edit Dx Codes":"Invalid Primary Diagnosis pop up",
            "End-to-End Success - Email Sent to Provider":"Successfully emailed Provider",
            "Missing Mandatory Field - Missing Enc/Txn Number":"Input File does not contain mandatory Enc/Txn numbers",
            "New/Unexpected Screen Element - IDX":"Unexpected IDX Pop up",
            "Review Required by Northwell - Pending Representative Review":"Business rules applied to pend txn for further review",
            "Specified Process Failure - Update Task Process":"Technical Error prevented the bot from adding a note to the transaction",
            "Specified Process Failure - Update DX Pointers":"Technical Error prevented the bot from updating Dx Pointers",
            "Missing Mandatory Field - Provider Email Address":"Input File does not contain mandatory Provider Email",
            "Unable to Click Hyperlink - Batch on Hold":"'Edit Transaction' hyperlink is not available; Likely Batch on Hold",
            "Unable to Click Hyperlink - Pending Feedback":"Technical Error prevented click of 'Pending Feedback' hyperlink",
            "Unable to Click Hyperlink - Pending Representative Review":"Technical Error prevented click of 'Pending Rep Review' hyperlink",
            "Validation Error - Encounter Number":"Unable to validate encounter number",
            "Account Not Found - No Patient Found":"No search results for patient; Likely worked by another user",
            "Unspecified Technical Failure - ":"Unspecified Technical Error",
        },
        "column_crosswalk": {
            "PTFULLNAME": "Patient Name",
            "INVNUM": "Enc Number",
            "CRN#": "Txn Number",
            "RetrievalStatus": "Retrieval Status",
            "RetrievalDescription": "Retrieval Description",
            "Reason": "Reason",
        },
        "carbon_copy": 'klawrence3@northwell.edu; ovicuna@northwell.edu; jcarney1@northwell.edu; gbunce@northwell.edu; mpuma@northwell.edu',
        "name_format": "{file_path}/GECB_TES6146_Outbound_{month_str}{day_str}{year_str}.xlsx",
    },
}